/**
 * Breach concept → Devvit build bridge.
 *
 * breach-concept/ holds the game exactly as designed: `*.dc.html` Design
 * Components plus `support.js` (the dc-runtime). Out of the box that runtime
 * loads React from unpkg, fetches sibling components over the network, `eval`s
 * each component's logic class, and pulls fonts/SFX from third-party origins —
 * none of which survives Reddit's webview CSP or Devvit's inlined entrypoints.
 *
 * sync() turns the concept into ordinary bundle inputs without touching the
 * concept files themselves:
 *   src/client/breach/generated/c-<name>.js    one per component: raw template + precompiled logic
 *   src/client/breach/generated/dc-runtime.js  support.js, patched (see PATCHES)
 *   public/{assets,sfx,fonts}                  copied art, vendored SFX + fonts
 *
 * Generated output is gitignored; edit breach-concept/ and it re-syncs
 * (on every build, and live under `npm run dev:tools`).
 */
import fs from 'node:fs';
import path from 'node:path';
import type { Plugin } from 'vite';

const ROOT = path.resolve(import.meta.dirname, '..');
const CONCEPT = path.join(ROOT, 'breach-concept');
const VENDOR = path.join(ROOT, 'vendor/breach');
const GEN = path.join(ROOT, 'src/client/breach/generated');
const PUBLIC = path.join(ROOT, 'public');

const PRECOMPILED = '/*dc-precompiled*/';
const LOGIC_RE = /(<script type="text\/x-dc" data-dc-script[^>]*>)([\s\S]*?)(<\/script>)/;

function replaceOnce(src: string, find: string, repl: string, what: string): string {
  const i = src.indexOf(find);
  if (i === -1) throw new Error(`[breach] support.js patch "${what}" no longer matches — dc-runtime changed upstream`);
  return src.slice(0, i) + repl + src.slice(i + find.length);
}

// Same-origin rewrites for each component source.
function localize(src: string): string {
  return src
    .replace(/<script src="\.\/support\.js"><\/script>\s*/g, '')
    .replace(/<link rel="preconnect" href="https:\/\/fonts\.googleapis\.com">/g, '')
    .replace(/<link href="https:\/\/fonts\.googleapis\.com\/css2[^"]*" rel="stylesheet">/g, '<link href="fonts/breach-fonts.css" rel="stylesheet">')
    .replace(/https:\/\/pub-[0-9a-f]+\.r2\.dev\/sfx\//g, 'sfx/');
}

function patchRuntime(src: string): string {
  let s = src;
  // 1. Logic classes come from precompiled factories instead of new Function().
  s = replaceOnce(
    s,
    'function evalDcLogic(src) {',
    `function evalDcLogic(src, name) {
    const pre = window.__dcLogicFactories;
    if (name && pre && typeof pre[name] === "function" && src.trim() === ${JSON.stringify(PRECOMPILED)})
      return pre[name](StreamableLogic, StreamableLogic, getReact());`,
    'evalDcLogic'
  );
  s = replaceOnce(s, 'const Cls = evalDcLogic(src);', 'const Cls = evalDcLogic(src, name);', 'updateJs');
  // 2. Boot from bundled source text (keeps camelCase attrs that DOM parsing loses).
  s = replaceOnce(
    s,
    'const parsed = parseDcDocument(doc);',
    'const parsed = window.__dcBootSrc ? parseDcText(window.__dcBootSrc) : parseDcDocument(doc);',
    'boot parse'
  );
  s = replaceOnce(
    s,
    'const rootName = rootNameForDocument(doc, location);',
    'const rootName = window.__dcBootName || rootNameForDocument(doc, location);',
    'boot name'
  );
  s = replaceOnce(s, 'if (!window.__resources) {', 'if (!window.__resources && !window.__dcBootSrc) {', 'boot refetch');
  s = replaceOnce(
    s,
    'const dc = doc.querySelector("x-dc");\n    const hostEl',
    'const dc = doc.querySelector("x-dc") || doc.body.appendChild(doc.createElement("x-dc"));\n    const hostEl',
    'boot host'
  );
  // 3. Page-level prop overrides (e.g. hide prototype-only UI in production).
  s = replaceOnce(
    s,
    'return h(Root, { ...defaults, ...entry.propOverrides || {} });',
    'return h(Root, { ...defaults, ...window.__dcBootProps || {}, ...entry.propOverrides || {} });',
    'root props'
  );
  return `/* eslint-disable */\n// GENERATED by tools/breach-plugin.ts from breach-concept/support.js — do not edit.\n${s}`;
}

function copyDir(from: string, to: string) {
  if (!fs.existsSync(from)) return;
  fs.mkdirSync(to, { recursive: true });
  for (const ent of fs.readdirSync(from, { withFileTypes: true })) {
    if (ent.name.startsWith('.')) continue;
    const a = path.join(from, ent.name);
    const b = path.join(to, ent.name);
    if (ent.isDirectory()) copyDir(a, b);
    else {
      const sa = fs.statSync(a);
      const sb = fs.existsSync(b) ? fs.statSync(b) : null;
      if (!sb || sb.size !== sa.size || sb.mtimeMs < sa.mtimeMs) fs.copyFileSync(a, b);
    }
  }
}

function writeIfChanged(file: string, content: string) {
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === content) return;
  fs.writeFileSync(file, content);
}

const slug = (name: string) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

export function syncBreach() {
  fs.mkdirSync(GEN, { recursive: true });
  const keep = new Set(['dc-runtime.js', 'dc-runtime.d.ts', 'component.d.ts']);
  for (const file of fs.readdirSync(CONCEPT).filter((f) => f.endsWith('.dc.html')).sort()) {
    const name = file.replace(/\.dc\.html$/, '');
    const raw = localize(fs.readFileSync(path.join(CONCEPT, file), 'utf8'));
    const m = LOGIC_RE.exec(raw);
    const js = m?.[2]?.trim() ? m[2] : null;
    const source = js ? raw.replace(LOGIC_RE, (_all, open: string, _js: string, close: string) => open + PRECOMPILED + close) : raw;
    const logic = js
      ? `function (DCLogic, StreamableLogic, React) {\n${js}\n;return (typeof Component !== "undefined" && Component) || undefined;\n}`
      : 'null';
    const base = `c-${slug(name)}`;
    keep.add(`${base}.js`).add(`${base}.d.ts`);
    writeIfChanged(
      path.join(GEN, `${base}.js`),
      `/* eslint-disable */\n// GENERATED by tools/breach-plugin.ts from breach-concept/${file} — do not edit.\n` +
        `export const name = ${JSON.stringify(name)};\nexport const source = ${JSON.stringify(source)};\nexport const logic = ${logic};\n`
    );
    writeIfChanged(path.join(GEN, `${base}.d.ts`), `export * from './component';\n`);
  }
  writeIfChanged(
    path.join(GEN, 'component.d.ts'),
    `export declare const name: string;\nexport declare const source: string;\n` +
      `export declare const logic: ((DCLogic: unknown, StreamableLogic: unknown, React: unknown) => unknown) | null;\n`
  );
  for (const f of fs.readdirSync(GEN)) if (!keep.has(f)) fs.rmSync(path.join(GEN, f));
  writeIfChanged(path.join(GEN, 'dc-runtime.js'), patchRuntime(fs.readFileSync(path.join(CONCEPT, 'support.js'), 'utf8')));
  writeIfChanged(path.join(GEN, 'dc-runtime.d.ts'), 'export {};\n');
  copyDir(path.join(CONCEPT, 'assets'), path.join(PUBLIC, 'assets'));
  copyDir(path.join(VENDOR, 'sfx'), path.join(PUBLIC, 'sfx'));
  copyDir(path.join(VENDOR, 'fonts'), path.join(PUBLIC, 'fonts'));
}

export function breach(): Plugin {
  let synced = false;
  return {
    name: 'breach-concept',
    enforce: 'pre',
    config() {
      // Must exist before Vite resolves entry imports.
      if (!synced) {
        syncBreach();
        synced = true;
      }
    },
    configureServer(server) {
      server.watcher.add(CONCEPT);
      let t: ReturnType<typeof setTimeout> | undefined;
      server.watcher.on('all', (_ev, file) => {
        if (!file.startsWith(CONCEPT)) return;
        clearTimeout(t);
        t = setTimeout(() => {
          try {
            syncBreach();
            server.ws.send({ type: 'full-reload' });
          } catch (e) {
            server.config.logger.error(String(e));
          }
        }, 150);
      });
    },
  };
}
